name: 🚀 post release
on:
  push:
    tags:
      - "v*"
permissions:
  contents: read

env:
  IMAGE_REGISTRY: ghcr.io
  GITHUB_REF_NAME: ${{ github.ref_name }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  ghcr:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flake-checker-action@main

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: nix build .#docker

      - name: Load Docker Image
        run: |
          docker load -i result

      - name: Push Docker Image
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          docker push $IMAGE_REGISTRY/$GITHUB_REPOSITORY:$VERSION
